{
 "title": "Ping service",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Dropped packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(ping_dropped_total[$__rate_interval])/rate(ping_sent_total[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ping latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ping_latency", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Sent and dropped packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ping_dropped_total[$__rate_interval])",
     "legendFormat": "Dropped {{host}}"
    },
    {
     "expr": "rate(ping_sent_total[$__rate_interval])",
     "legendFormat": "Sent {{host}}"
    }
   ]
  },
  {
   "title": "Monitor ping window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "ping_window", "legendFormat": "{{host}}" }
   ]
  }
 ]
}