apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ping
  name: ping-deployment
  labels:
    app: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: mkolman/ping-service:v1.0.0
        args: ["google.com", "live.com", "facebook.com"]
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: ping
  name: ping-service
  labels:
    app: ping-service
spec:
  selector:
    app: ping
  ports:
  - name: ping-port
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: ping
  labels:
    release: monitoring
  name: ping-monitor
spec:
  selector:
    matchLabels:
      app: ping-service
  endpoints:
  - port: ping-port
